### PR TITLE
Added the ability to change the PHP version in the settings.

### LINKED ISSUE #19: Error Highlighting Shifted
In this screen shot you can see that the highlighting for the error "undeclared interface class 'UserInterface'" is over ", EquatableIn" instead of "UserInterface".

screen shot 2016-01-20 at 18 15 50

It's possible that I have configured things incorrectly. I'm just getting back into PHP have many years. However I think I've followed the instructions. I'm running PHPLint 2.1_20151116 installed via Homebrew.(https://github.com/rgant/homebrew-php/blob/up_phplint/Formula/phplint.rb Updating the formula to the latest version here. However this didn't work on 20150305 either.) Sublime Text 3 build 3083, Package Control & SublimeLinter are up to date.

Any help resolving this would be appreciated.

### PR DESCRIPTION
**Pull request by holtjohnson**
Fixes #19, most work done by @josephtaylor-mn in PR #25.
Made last change requested in #28 (Squashing all changes into one commit).

Will also close #25 & close #28.

### CODE REVIEW

**Comment by ajmichels** [comment]
For future reference if you just push updated to the branch from which you create a PR it will automatically update the PR, no need to close it and create a new one. Then any comments or discussion related to the PR will be preserved. It will also show how the PR changed over time.

**Comment by ajmichels** [comment]
I will try to test and merge this tonight after work.

**Comment by holtjohnson** [comment]
Thanks for taking a look and being so quick to respond! I appreciate your work!

Also, I'm familiar with GitHub's ability to follow changes made to a branch in a PR. I like the ability and wish I could use it, but the only way I know to squash multiple commits into one on GitHub requires me to create a new branch. With Git alone on my own machine I know I can squash changes via rebase, but I know it's bad practice and a hassle to push a rebase upstream. Is there something I'm missing?

**Comment by holtjohnson** [comment]
I haven't had time to look at it yet, but someone told me this evening GitHub has a solution/feature for this: https://github.com/blog/2141-squash-your-commits

**Comment by holtjohnson** [comment]
Any news @ajmichels?

**Comment by ajmichels** [comment]
Sorry, I have been very busy both at work and at home.

**Comment by braver** [comment]
There's a better and easier way to solve this: https://github.com/SublimeLinter/SublimeLinter-phplint/pull/32/commits/f56e4f7dd5ed1a96f6e19f5ff2c34b93476de8a7

**Pull request closed without merging**
